name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Trigger workflow on push to main
  workflow_dispatch:     # Allow manual triggering from Actions tab

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          package-manager: npm   # <-- specify your package manager (npm, pnpm, or yarn)
          path: .               # optional if Astro project is at repo root
          node-version: 20      # optional, defaults to 20
        # env:
          # PUBLIC_POKEAPI: 'https://pokeapi.co/api/v2' # Example env variable (optional)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
